version: '3'

services:
  app:
    image: rojima1/python
    privileged: true
    command: emacs
    working_dir: /home/developer/jellyfish-eye-k
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/home/developer/jellyfish-eye-k
      - /tmp/.X11-unix:/tmp/.X11-unix
